/*
Deployment script for SVESTENIK

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "SVESTENIK"
:setvar DefaultFilePrefix "SVESTENIK"
:setvar DefaultDataPath "C:\Users\aca\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\MSSQLLocalDB\"
:setvar DefaultLogPath "C:\Users\aca\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\MSSQLLocalDB\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Creating [dbo].[Akcija]...';


GO
CREATE TABLE [dbo].[Akcija] (
    [Id]             INT  IDENTITY (1, 1) NOT NULL,
    [popust]         INT  NULL,
    [DatumPocetka]   DATE NULL,
    [DatumZavrsetka] DATE NULL,
    [active]         INT  NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[DodatnaUsluga]...';


GO
CREATE TABLE [dbo].[DodatnaUsluga] (
    [Id]     INT          IDENTITY (1, 1) NOT NULL,
    [Naziv]  VARCHAR (50) NULL,
    [Cena]   INT          NULL,
    [active] INT          NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[Korisnik]...';


GO
CREATE TABLE [dbo].[Korisnik] (
    [Id]             INT          IDENTITY (1, 1) NOT NULL,
    [TipKorisnikaId] INT          NULL,
    [Ime]            VARCHAR (50) NULL,
    [Prezime]        VARCHAR (50) NULL,
    [JMBG]           VARCHAR (50) NULL,
    [DatumRodjenja]  DATETIME     NULL,
    [KorisnickoIme]  VARCHAR (20) NULL,
    [Lozinka]        VARCHAR (20) NULL,
    [active]         INT          NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[Namestaj]...';


GO
CREATE TABLE [dbo].[Namestaj] (
    [Id]                INT           IDENTITY (1, 1) NOT NULL,
    [TipNamestajaId]    INT           NULL,
    [AkcijaId]          INT           NULL,
    [Naziv]             VARCHAR (100) NULL,
    [Sifra]             VARCHAR (50)  NULL,
    [Cena]              INT           NULL,
    [KolicinaUMagacinu] INT           NULL,
    [active]            INT           NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[Prodaja]...';


GO
CREATE TABLE [dbo].[Prodaja] (
    [Id]              INT             IDENTITY (1, 1) NOT NULL,
    [Kupac]           VARCHAR (50)    NULL,
    [BrojRacuna]      VARCHAR (50)    NULL,
    [DatumProdaje]    DATE            NULL,
    [NamestajId]      INT             NULL,
    [DodatnaUslugaId] INT             NULL,
    [UkupnaCena]      DECIMAL (10, 2) NULL,
    [active]          INT             NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[Salon]...';


GO
CREATE TABLE [dbo].[Salon] (
    [Id]          INT          IDENTITY (1, 1) NOT NULL,
    [Naziv]       VARCHAR (50) NULL,
    [Adresa]      VARCHAR (50) NULL,
    [Telefon]     VARCHAR (50) NULL,
    [Email]       VARCHAR (50) NULL,
    [Web]         VARCHAR (50) NULL,
    [Pib]         VARCHAR (50) NULL,
    [MaticniBroj] VARCHAR (50) NULL,
    [ZiroRacun]   VARCHAR (50) NULL,
    [active]      INT          NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[TipKorisnika]...';


GO
CREATE TABLE [dbo].[TipKorisnika] (
    [Id]      INT          IDENTITY (1, 1) NOT NULL,
    [Naziv]   VARCHAR (80) NULL,
    [Opis]    VARCHAR (80) NULL,
    [Obrisan] BIT          NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[TipNamestaja]...';


GO
CREATE TABLE [dbo].[TipNamestaja] (
    [Id]     INT          IDENTITY (1, 1) NOT NULL,
    [Naziv]  VARCHAR (80) NULL,
    [Opis]   VARCHAR (80) NULL,
    [active] INT          NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating unnamed constraint on [dbo].[Korisnik]...';


GO
ALTER TABLE [dbo].[Korisnik] WITH NOCHECK
    ADD FOREIGN KEY ([TipKorisnikaId]) REFERENCES [dbo].[TipKorisnika] ([Id]);


GO
PRINT N'Creating unnamed constraint on [dbo].[Namestaj]...';


GO
ALTER TABLE [dbo].[Namestaj] WITH NOCHECK
    ADD FOREIGN KEY ([TipNamestajaId]) REFERENCES [dbo].[TipNamestaja] ([Id]);


GO
PRINT N'Creating unnamed constraint on [dbo].[Prodaja]...';


GO
ALTER TABLE [dbo].[Prodaja] WITH NOCHECK
    ADD FOREIGN KEY ([DodatnaUslugaId]) REFERENCES [dbo].[DodatnaUsluga] ([Id]);


GO
PRINT N'Checking existing data against newly created constraints';


GO
USE [$(DatabaseName)];


GO
CREATE TABLE [#__checkStatus] (
    id           INT            IDENTITY (1, 1) PRIMARY KEY CLUSTERED,
    [Schema]     NVARCHAR (256),
    [Table]      NVARCHAR (256),
    [Constraint] NVARCHAR (256)
);

SET NOCOUNT ON;

DECLARE tableconstraintnames CURSOR LOCAL FORWARD_ONLY
    FOR SELECT SCHEMA_NAME([schema_id]),
               OBJECT_NAME([parent_object_id]),
               [name],
               0
        FROM   [sys].[objects]
        WHERE  [parent_object_id] IN (OBJECT_ID(N'dbo.Korisnik'), OBJECT_ID(N'dbo.Namestaj'), OBJECT_ID(N'dbo.Prodaja'))
               AND [type] IN (N'F', N'C')
                   AND [object_id] IN (SELECT [object_id]
                                       FROM   [sys].[check_constraints]
                                       WHERE  [is_not_trusted] <> 0
                                              AND [is_disabled] = 0
                                       UNION
                                       SELECT [object_id]
                                       FROM   [sys].[foreign_keys]
                                       WHERE  [is_not_trusted] <> 0
                                              AND [is_disabled] = 0);

DECLARE @schemaname AS NVARCHAR (256);

DECLARE @tablename AS NVARCHAR (256);

DECLARE @checkname AS NVARCHAR (256);

DECLARE @is_not_trusted AS INT;

DECLARE @statement AS NVARCHAR (1024);

BEGIN TRY
    OPEN tableconstraintnames;
    FETCH tableconstraintnames INTO @schemaname, @tablename, @checkname, @is_not_trusted;
    WHILE @@fetch_status = 0
        BEGIN
            PRINT N'Checking constraint: ' + @checkname + N' [' + @schemaname + N'].[' + @tablename + N']';
            SET @statement = N'ALTER TABLE [' + @schemaname + N'].[' + @tablename + N'] WITH ' + CASE @is_not_trusted WHEN 0 THEN N'CHECK' ELSE N'NOCHECK' END + N' CHECK CONSTRAINT [' + @checkname + N']';
            BEGIN TRY
                EXECUTE [sp_executesql] @statement;
            END TRY
            BEGIN CATCH
                INSERT  [#__checkStatus] ([Schema], [Table], [Constraint])
                VALUES                  (@schemaname, @tablename, @checkname);
            END CATCH
            FETCH tableconstraintnames INTO @schemaname, @tablename, @checkname, @is_not_trusted;
        END
END TRY
BEGIN CATCH
    PRINT ERROR_MESSAGE();
END CATCH

IF CURSOR_STATUS(N'LOCAL', N'tableconstraintnames') >= 0
    CLOSE tableconstraintnames;

IF CURSOR_STATUS(N'LOCAL', N'tableconstraintnames') = -1
    DEALLOCATE tableconstraintnames;

SELECT N'Constraint verification failed:' + [Schema] + N'.' + [Table] + N',' + [Constraint]
FROM   [#__checkStatus];

IF @@ROWCOUNT > 0
    BEGIN
        DROP TABLE [#__checkStatus];
        RAISERROR (N'An error occurred while verifying constraints', 16, 127);
    END

SET NOCOUNT OFF;

DROP TABLE [#__checkStatus];


GO
PRINT N'Update complete.';


GO
